#!/bin/bash

POSTFIX_HOSTMASTER="change-me.com" # change it to your domainname

# Define which sql server to use.
# SQL_SERVER="psql"
type mysql >/dev/null 2>&1 && SQL_SERVER="mysql" || type psql >/dev/null 2>&1 && SQL_SERVER="psql"

FIREWALL_RULES_UP_FILENAME="/etc/iptables.up.rules"
FIREWALL_SENDMAIL=25
FIREWALL_SENDMAIL_SUBMISSION=587
FIREWALL_IMAP=143
FIREWALL_IMAPS=993
FIREWALL_POP=110
FIREWALL_POPS=465
FIREWALL_POPS3=993
