#!/bin/bash
DEBIAN_FRONTEND=noninteractive

set -e # Exit immediately if a command exits with a non-zero status.
set -u #

source ./config

firewall_delete_rule () {
  grep -v "$1" $FIREWALL_RULES_UP_FILENAME > /etc/iptables.new.rules
  iptables-restore < /etc/iptables.new.rules
  iptables-save > /etc/iptables.up.rules
}

firewall_add_rule () {
  firewall_delete_rule "dport $1"
  firewall_delete_rule "sport $1"
  iptables -A INPUT -p tcp --dport $1 -m state --state NEW,ESTABLISHED -j ACCEPT
  iptables -A OUTPUT -p tcp --sport $1 -m state --state ESTABLISHED -j ACCEPT
  iptables-save > /etc/iptables.up.rules
}

echo -e "\n********************************************************"
echo -e "* Installing postfix"
echo -e "********************************************************"

debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
debconf-set-selections <<< "postfix postfix/mailname string $POSTFIX_HOSTMASTER"

aptitude -y -q install postfix

echo -e "\n********************************************************"
echo -e "* Setting firewall"
echo -e "********************************************************"

# Allow Sendmail
[ ! -z "$FIREWALL_SENDMAIL" ] && {
  firewall_add_rule $FIREWALL_SENDMAIL
}

# Allow sendmail via submission port
[ ! -z "$FIREWALL_SENDMAIL_SUBMISSION" ] && {
  firewall_add_rule $FIREWALL_SENDMAIL_SUBMISSION
}

# Allow IMAP
[ ! -z "$FIREWALL_IMAP" ] && {
  firewall_add_rule $FIREWALL_IMAP
}

# Allow IMAPs
[ ! -z "$FIREWALL_IMAPS" ] && {
  firewall_add_rule $FIREWALL_IMAPS
}

# Allow pop
[ ! -z "$FIREWALL_POP" ] && {
  firewall_add_rule $FIREWALL_POP
}

# Allow pops
[ ! -z "$FIREWALL_POPS" ] && {
  firewall_add_rule $FIREWALL_POPS
}

# Allow pop3s
[ ! -z "$FIREWALL_POPS3" ] && {
  firewall_add_rule $FIREWALL_POPS3
}

echo -e "\n********************************************************"
echo -e "* Making database for user authentication"
echo -e "********************************************************"

[ -z "$SQL_SERVER" ] && {
  echo "* Missing SQL server. Can't find any one installed :("
  exit 1
}

case "${SQL_SERVER}" in
  psql)
    #TODO sql script that make DB for dovecot
  ;;
  mysql)
    #TODO sql script that make DB for dovecot
  ;;
esac

echo -e "DONE install postfix"
